name: Build the UI

on:
  workflow_call:
  workflow_dispatch:
  pull_request:
    paths:
      - "frontend/**"
      - ".github/workflows/build-frontend.yml"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # Freed up the disk space just in case if it gives error later
      - name: Free up disk space
        run: |
          sudo swapoff -a
          sudo rm -f /swapfile
          sudo apt clean
          docker rmi $(docker image ls -aq)
          df -h

      - uses: actions/checkout@v4

      - name: Install Bowtie
        uses: ./

      - name: Generate all implementations (harness)'s metadata
        run: |
          bowtie info $(ls implementations/ | sed 's/^/-i /') --format json > implementations.json

      - uses: actions/setup-node@v4
        with:
          node-version: 18.x

      - uses: pnpm/action-setup@v3
        with:
          version: 8
          run_install: false

      - name: Get pnpm store directory
        shell: bash
        run: |
          echo "STORE_PATH=$(pnpm store path --silent)" >> $GITHUB_ENV

      - uses: actions/cache@v4
        name: Setup pnpm cache
        with:
          path: ${{ env.STORE_PATH }}
          key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-store-

      - name: Install dependencies
        run: pnpm install --dir frontend --frozen-lockfile --strict-peer-dependencies

      - name: Build the UI
        run: pnpm run --dir frontend build --base=${{ vars.BOWTIE_BASE_URL || '/bowtie' }}

      - uses: actions/upload-artifact@v3
        with:
          name: frontend-build
          path: |
            frontend/build
            implementations.json
